export const FC = {
    "POOL_POOLING_INTERVAL" :  1000 * 1,
    "WORKER_POOLING_INTERVAL" :  1000 * 1,
    "BLOCKS_POOLING_INTERVAL" :  1000 * 1,
    "BLOCK_HISTORY_POOLING_INTERVAL" :  1000 * 1,

    "HYCON_EXPLORER": "http://localhost:2442/"
}

